# Generated by Django 5.0.8 on 2025-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
