# Generated by Django 5.0.8 on 2025-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_records_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
